-- Data dictionary for the cell allocation schema.
--
-- These comments are read by SchemaSpy (published to GitHub Pages) and by anything else that reads
-- pg_description, including the CSV export for the MOJ Data Catalogue / Glue. Keep them updated when
-- columns are added or their meaning changes - SchemaCommentsTest fails the build if a table or column
-- has no comment.
--
-- This restates the handful of comments already added by V2 to V5 rather than leaving them scattered,
-- so the whole dictionary reads as one document. COMMENT ON replaces in place, so re-issuing a comment
-- is safe and idempotent.
--
-- Every column comment ends with a sensitivity classification:
--
--   [Sensitivity: NONE]                - not personal data in itself (keys, timestamps, process flags)
--   [Sensitivity: PERSONAL]            - personal data about a prisoner: identifies or locates them
--   [Sensitivity: STAFF]               - personal data about a member of staff, typically the username
--                                        that performed an action
--   [Sensitivity: SPECIAL-CATEGORY]    - UK GDPR Article 9 data (health, sexuality, religion, race,
--                                        gender reassignment) or criminal offence data under Article 10
--   [Sensitivity: OFFICIAL-SENSITIVE]  - not personal data, but damaging if disclosed
--
-- STAFF is still personal data and still in scope for a staff member's own subject access request. It is
-- separated from PERSONAL so that an extract about prisoners can be reasoned about without staff columns
-- inflating the count, and so staff data can be dropped or pseudonymised independently.
--
-- Three things to understand before using these classifications:
--
--   1. They describe the column's own content, not the row's. Every row here is a named prisoner being
--      moved between cells, so the whole record is personal data about that prisoner however an
--      individual column is tagged. That is what matters for a subject access request.
--
--   2. **reason_code is special category, and that is not obvious from its name.** It is a short code,
--      but the CHG_HOUS_RSN vocabulary it draws on includes HOSP (Healthcare), VP (Vulnerable
--      Prisoner), SS (Someone's safety), CON (Conflict with Other Prisoners) and BEH (Behaviour).
--      Knowing that a named prisoner was moved for one of those reveals their health or safeguarding
--      status. The sensitivity is in the values, not the field label - see reference-data.csv for the
--      full list.
--
--   3. **Every free-text column should be assumed to contain more than its question asks.** comment_text
--      asks only why someone was moved; in practice it records violence, self harm, bullying and health.
--      Free text is classified on what staff actually write in it.


-- ---------------------------------------------------------------------------------------------------
-- cell_movement - movements this service recorded
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE cell_movement IS 'A prisoner being moved to a different cell, with the reason and the explanation. Replaces whereabouts-api''s CELL_MOVE_REASON: the important difference is that the explanation is held here rather than only in a case note, so the case note becomes a derived artefact that can be recreated, and "what happened" can be served in one hop.';
COMMENT ON COLUMN cell_movement.id IS 'Primary key. A UUIDv7 generated by the application. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement.prisoner_number IS 'NOMIS offender number of the prisoner who was moved. The identifier that makes every row in this table personal data about that prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.booking_id IS 'NOMIS booking id, the custody period the move belongs to. Resolved from prisoner-search, never accepted from the caller: prison-api still identifies a booking this way, but bookingId is not part of this service''s API contract. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.bed_assignment_sequence IS 'Position of this move in the prisoner''s bed assignment history, returned by prison-api once the move lands. Null while the movement is PENDING, and also null when the prisoner was already in the destination cell - prison-api treats that as a successful no-op. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.from_location_key IS 'Where the prisoner was immediately before the move, as {prisonId}-{pathHierarchy}, as best the service knew at the time. prisoner-search is a near real-time projection rather than a live read, so this can lag, and it is null if it could not be resolved. Never treat it as authoritative - NOMIS validates the real state during the move. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.to_location_key IS 'The cell the prisoner was moved to, as {prisonId}-{pathHierarchy}. Locates a named prisoner. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.reason_code IS 'Why the prisoner was moved, as a CHG_HOUS_RSN code such as HOSP or VP. Also used as the case note subType, which is what caps it at 12 characters. Special category because of the values it takes, not the field itself: the vocabulary includes Healthcare, Vulnerable Prisoner and Someone''s safety, so the code can reveal a named prisoner''s health or safeguarding status. There is deliberately no check constraint - see reference-data.csv for the permitted values. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN cell_movement.comment_text IS 'The mover''s free-text explanation. Always present for a CELL_MOVE, never present for a CELL_SWAP, because the swap journey does not ask for one. Deliberately unbounded: the case notes service is the source of truth for case note text and imposes no limit, so bounding it here would invent a constraint the system of record does not have. In practice it records violence, self harm, bullying and health, so treat it as Article 9 data whatever the question asked. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN cell_movement.case_note_uuid IS 'The case note created for this move, by its canonical UUID. Null for a cell swap, which creates none, and null on a CASE_NOTE_FAILED row. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement.case_note_legacy_id IS 'The numeric case note id. Exists for rows migrated from whereabouts and is not populated by this service - the case notes service is UUID canonical. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement.occurred_at IS 'When the move happened. With prisoner_number and to_location_key this places a named prisoner in a specific cell at a specific time. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.recorded_by IS 'The signed-in user who made the move, which is also who NOMIS records as having made it. [Sensitivity: STAFF]';
COMMENT ON COLUMN cell_movement.status IS 'How far the movement got: PENDING, COMPLETED or CASE_NOTE_FAILED. Stored as text with no check constraint, so adding a state later is a code change rather than a migration. See reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement.movement_type IS 'Which journey the user took: CELL_MOVE or CELL_SWAP. Recorded rather than inferred from the destination key, because once prison-api''s dedicated swap endpoint is retired a swap becomes mechanically indistinguishable from an ordinary move to a CSWAP location, and this column is the only surviving record of which it was. See reference-data.csv. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement.from_location_id IS 'locations-inside-prison UUID for from_location_key at the time of the move. The durable identity: path hierarchies can be renamed, so the key may not identify the same cell across years of history. Best effort - resolution never blocks a move, so this is null on older rows and where locations-inside-prison could not be reached. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement.to_location_id IS 'locations-inside-prison UUID for to_location_key at the time of the move. Same durable-identity rule and the same best-effort caveat as from_location_id. [Sensitivity: PERSONAL]';


-- ---------------------------------------------------------------------------------------------------
-- cell_movement_nomis - movements inherited from whereabouts
-- ---------------------------------------------------------------------------------------------------

COMMENT ON TABLE cell_movement_nomis IS 'Cell move reasons inherited from whereabouts-api CELL_MOVE_REASON: the link as whereabouts held it, plus what this service has resolved from the case note it points at. Kept as a separate table rather than as rows in cell_movement because these rows are a different thing - the source carries three columns where cell_movement has sixteen, and merging them would mean dropping most of cell_movement''s not-null constraints. Which table a row is in is therefore the answer to "is this ours or inherited?".';
COMMENT ON COLUMN cell_movement_nomis.booking_id IS 'NOMIS booking id, copied verbatim from whereabouts. Part of the primary key with bed_assignment_sequence, which is the natural key in the source and makes both the backfill and the read-through idempotent. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement_nomis.bed_assignment_sequence IS 'Position of the move in the booking''s bed assignment history, copied verbatim from whereabouts. Part of the primary key. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement_nomis.case_note_legacy_id IS 'The numeric case note id, as whereabouts recorded it. The explanation of the move lives in that case note and nowhere else: whereabouts never stored the text, which is exactly the weakness cell_movement.comment_text fixes for movements recorded by this service. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement_nomis.prisoner_number IS 'NOMIS offender number, resolved from the case note rather than copied - the source table held only a booking id. Null until the row has been enriched. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement_nomis.reason_code IS 'Why the prisoner was moved, as a CHG_HOUS_RSN code, surviving only as the case note''s subType. Special category for the same reason as cell_movement.reason_code: the vocabulary includes Healthcare, Vulnerable Prisoner and Someone''s safety. Null until the row has been enriched. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN cell_movement_nomis.comment_text IS 'The explanation of the move, read from the case note. Same content and the same risks as cell_movement.comment_text - assume violence, self harm and health. Null until the row has been enriched. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN cell_movement_nomis.case_note_uuid IS 'The case note''s canonical UUID, learned when the note is first read. The legacy id is what whereabouts held; this is what the case notes service prefers to be asked for. [Sensitivity: NONE]';
COMMENT ON COLUMN cell_movement_nomis.occurred_at IS 'When the move happened, taken from the case note''s occurrenceDateTime, which whereabouts set to the moment of the move. Null until the row has been enriched. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN cell_movement_nomis.enriched_at IS 'When the enrichment was resolved. Null means it has not been attempted yet, or the last attempt hit a transient failure and should be retried. Set while the note fields are still null means the case note is definitively gone and there is nothing more to fetch. [Sensitivity: NONE]';
